SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Importing Checksqlite3 Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('1','Checksqlite3 Download','Checksqlite3 Download','exec .\\resources\\cmd\\getupdates.bat /plugins/Checksqlite3 Checksqlite3'); 
SELECT 'Importing Checksqlite3 Plugin SCRIPT DONE'; 	
SELECT 'Importing core.zip core.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('2','core.zip core.zip Download','core.zip core.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/core.zip core.zip core.zip core.zip'); 
SELECT 'Importing core.zip core.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing all.zip all.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('3','all.zip all.zip Download','all.zip all.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/all.zip all.zip all.zip all.zip'); 
SELECT 'Importing all.zip all.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing apache-maven.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('4','apache-maven.zip Download','apache-maven.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/apache-maven.zip apache-maven.zip'); 
SELECT 'Importing apache-maven.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing apache-ant.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('5','apache-ant.zip Download','apache-ant.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/apache-ant.zip apache-ant.zip'); 
SELECT 'Importing apache-ant.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2linkcli.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('6','lc2linkcli.zip Download','lc2linkcli.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2linkcli.zip lc2linkcli.zip'); 
SELECT 'Importing lc2linkcli.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing excelimport.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('7','excelimport.zip Download','excelimport.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/excelimport.zip excelimport.zip'); 
SELECT 'Importing excelimport.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2irc.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('8','lc2irc.zip Download','lc2irc.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2irc.zip lc2irc.zip'); 
SELECT 'Importing lc2irc.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing graburls.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('9','graburls.zip Download','graburls.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/graburls.zip graburls.zip'); 
SELECT 'Importing graburls.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('10','LC2RotatingTorproxy.zip Download','LC2RotatingTorproxy.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2RotatingTorproxy.zip LC2RotatingTorproxy.zip'); 
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2process.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('11','lc2process.zip Download','lc2process.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2process.zip lc2process.zip'); 
SELECT 'Importing lc2process.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing org.letztechance.domain.web.GrabUrls.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('12','org.letztechance.domain.web.GrabUrls.zip Download','org.letztechance.domain.web.GrabUrls.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/org.letztechance.domain.web.GrabUrls.zip org.letztechance.domain.web.GrabUrls.zip'); 
SELECT 'Importing org.letztechance.domain.web.GrabUrls.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2php.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('13','lc2php.zip Download','lc2php.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2php.zip lc2php.zip'); 
SELECT 'Importing lc2php.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2mysqldocker.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('14','lc2mysqldocker.zip Download','lc2mysqldocker.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2mysqldocker.zip lc2mysqldocker.zip'); 
SELECT 'Importing lc2mysqldocker.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2Python.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('15','LC2Python.zip Download','LC2Python.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2Python.zip LC2Python.zip'); 
SELECT 'Importing LC2Python.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing postgresdocker.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('16','postgresdocker.zip Download','postgresdocker.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/postgresdocker.zip postgresdocker.zip'); 
SELECT 'Importing postgresdocker.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2bat2exe.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('17','LC2bat2exe.zip Download','LC2bat2exe.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2bat2exe.zip LC2bat2exe.zip'); 
SELECT 'Importing LC2bat2exe.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2DockerSonarCube.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('18','LC2DockerSonarCube.zip Download','LC2DockerSonarCube.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2DockerSonarCube.zip LC2DockerSonarCube.zip'); 
SELECT 'Importing LC2DockerSonarCube.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2DockerJenkins.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('19','LC2DockerJenkins.zip Download','LC2DockerJenkins.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2DockerJenkins.zip LC2DockerJenkins.zip'); 
SELECT 'Importing LC2DockerJenkins.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2DockerPHPMyAdmin.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('20','LC2DockerPHPMyAdmin.zip Download','LC2DockerPHPMyAdmin.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2DockerPHPMyAdmin.zip LC2DockerPHPMyAdmin.zip'); 
SELECT 'Importing LC2DockerPHPMyAdmin.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2J-Lawyer.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('21','LC2J-Lawyer.zip Download','LC2J-Lawyer.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2J-Lawyer.zip LC2J-Lawyer.zip'); 
SELECT 'Importing LC2J-Lawyer.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2HTTPAnalysis.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('22','LC2HTTPAnalysis.zip Download','LC2HTTPAnalysis.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2HTTPAnalysis.zip LC2HTTPAnalysis.zip'); 
SELECT 'Importing LC2HTTPAnalysis.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2Grafana.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('23','LC2Grafana.zip Download','LC2Grafana.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2Grafana.zip LC2Grafana.zip'); 
SELECT 'Importing LC2Grafana.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2ELK.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('23','LC2ELK.zip Download','LC2ELK.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2ELK.zip LC2ELK.zip'); 
SELECT 'Importing LC2ELK.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2Kubernetes.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('24','LC2Kubernetes.zip Download','LC2Kubernetes.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2Kubernetes.zip LC2Kubernetes.zip'); 
SELECT 'Importing LC2Kubernetes.zip Plugin SCRIPT DONE'; 	
SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Running SQL plugins import DONE'; 
