SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Importing Checksqlite3 Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('Checksqlite3 Download','Checksqlite3 Download','exec .\\resources\\cmd\\getupdates.bat /plugins/Checksqlite3 Checksqlite3'); 
SELECT 'Importing Checksqlite3 Plugin SCRIPT DONE'; 	
SELECT 'Importing core.zip core.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('core.zip core.zip Download','core.zip core.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/core.zip core.zip core.zip core.zip'); 
SELECT 'Importing core.zip core.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing all.zip all.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('all.zip all.zip Download','all.zip all.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/all.zip all.zip all.zip all.zip'); 
SELECT 'Importing all.zip all.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2php.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('lc2php.zip Download','lc2php.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2php.zip lc2php.zip'); 
SELECT 'Importing lc2php.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing excelimport.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('excelimport.zip Download','excelimport.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/excelimport.zip excelimport.zip'); 
SELECT 'Importing excelimport.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing python.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('python.zip Download','python.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/python.zip python.zip'); 
SELECT 'Importing python.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing mysqldocker.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('mysqldocker.zip Download','mysqldocker.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/mysqldocker.zip mysqldocker.zip'); 
SELECT 'Importing mysqldocker.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing apache-maven.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('apache-maven.zip Download','apache-maven.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/apache-maven.zip apache-maven.zip'); 
SELECT 'Importing apache-maven.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2irc.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('lc2irc.zip Download','lc2irc.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2irc.zip lc2irc.zip'); 
SELECT 'Importing lc2irc.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing graburls.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('graburls.zip Download','graburls.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/graburls.zip graburls.zip'); 
SELECT 'Importing graburls.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(first_name,name,url)values('LC2RotatingTorproxy.zip Download','LC2RotatingTorproxy.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2RotatingTorproxy.zip LC2RotatingTorproxy.zip'); 
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT DONE'; 	
SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Running SQL plugins import DONE'; 
