SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Importing Checksqlite3 Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('1','Checksqlite3 Download','Checksqlite3 Download','exec .\\resources\\cmd\\getupdates.bat /plugins/Checksqlite3 Checksqlite3'); 
SELECT 'Importing Checksqlite3 Plugin SCRIPT DONE'; 	
SELECT 'Importing core.zip core.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('2','core.zip core.zip Download','core.zip core.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/core.zip core.zip core.zip core.zip'); 
SELECT 'Importing core.zip core.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing all.zip all.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('3','all.zip all.zip Download','all.zip all.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/all.zip all.zip all.zip all.zip'); 
SELECT 'Importing all.zip all.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing apache-maven.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('4','apache-maven.zip Download','apache-maven.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/apache-maven.zip apache-maven.zip'); 
SELECT 'Importing apache-maven.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing apache-ant.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('5','apache-ant.zip Download','apache-ant.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/apache-ant.zip apache-ant.zip'); 
SELECT 'Importing apache-ant.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2linkcli.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('6','lc2linkcli.zip Download','lc2linkcli.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2linkcli.zip lc2linkcli.zip'); 
SELECT 'Importing lc2linkcli.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing excelimport.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('7','excelimport.zip Download','excelimport.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/excelimport.zip excelimport.zip'); 
SELECT 'Importing excelimport.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2irc.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('8','lc2irc.zip Download','lc2irc.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2irc.zip lc2irc.zip'); 
SELECT 'Importing lc2irc.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing graburls.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('9','graburls.zip Download','graburls.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/graburls.zip graburls.zip'); 
SELECT 'Importing graburls.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('10','LC2RotatingTorproxy.zip Download','LC2RotatingTorproxy.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/LC2RotatingTorproxy.zip LC2RotatingTorproxy.zip'); 
SELECT 'Importing LC2RotatingTorproxy.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2process.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('11','lc2process.zip Download','lc2process.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2process.zip lc2process.zip'); 
SELECT 'Importing lc2process.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing org.letztechance.domain.web.GrabUrls.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('12','org.letztechance.domain.web.GrabUrls.zip Download','org.letztechance.domain.web.GrabUrls.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/org.letztechance.domain.web.GrabUrls.zip org.letztechance.domain.web.GrabUrls.zip'); 
SELECT 'Importing org.letztechance.domain.web.GrabUrls.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing lc2php.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('13','lc2php.zip Download','lc2php.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/lc2php.zip lc2php.zip'); 
SELECT 'Importing lc2php.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing mysqldocker.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('14','mysqldocker.zip Download','mysqldocker.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/mysqldocker.zip mysqldocker.zip'); 
SELECT 'Importing mysqldocker.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing python.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('15','python.zip Download','python.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/python.zip python.zip'); 
SELECT 'Importing python.zip Plugin SCRIPT DONE'; 	
SELECT 'Importing postgresdocker.zip Plugin SCRIPT'; 	
INSERT OR REPLACE INTO plugins(person_id,first_name,name,url)values('16','postgresdocker.zip Download','postgresdocker.zip Download','exec .\\resources\\cmd\\getupdates.bat /plugins/postgresdocker.zip postgresdocker.zip'); 
SELECT 'Importing postgresdocker.zip Plugin SCRIPT DONE'; 	
SELECT 'Plugins count ',count(*) from plugins; 
SELECT 'Running SQL plugins import DONE'; 
